project_identifier: "motion-plus-installer"
base_path: .
preserve_hierarchy: true

files:
  - source: "docs/ja/**/*.md"
    translation: "docs/%two_letters_code%/%original_path%"
    ignore:
      - "docs/ja/_plan.md"

  - source: "README/ja.md"
    # Place translated README files as `README/<two_letters_code>.md`, e.g. `README/en.md`
    translation: "README/%two_letters_code%.md"