project_identifier: "motion-plus-installer"
base_path: .
preserve_hierarchy: true

files:
  - source: "docs/config.ts"
    translation: "docs/%two_letters_code%/config.ts"

  - base_path: "docs/ja"
    source: "**/*.md"
    # Preserve docs subdirectory structure by making original path relative to docs/ja
    translation: "docs/%two_letters_code%/%original_path%"
    ignore:
      - "_plan.md"
      - "config.ts"

  - source: "README/ja.md"
    translation: "README/%two_letters_code%.md"